// Generated by Melange

import * as Caml_option from "melange.js/caml_option.js";
import * as Curry from "melange.js/curry.js";

function negb(param) {
  if (param === /* True */ 0) {
    return /* False */ 1;
  } else {
    return /* True */ 0;
  }
}

function fst(param) {
  return param._0;
}

function snd(param) {
  return param._1;
}

function length(param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* O */ 0;
  } else {
    return {
      TAG: /* S */ 0,
      _0: length(param._1)
    };
  }
}

function app(l, m) {
  if (/* tag */ typeof l === "number" || typeof l === "string") {
    return m;
  } else {
    return {
      TAG: /* Cons */ 0,
      _0: l._0,
      _1: app(l._1, m)
    };
  }
}

function add(n, m) {
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    return m;
  } else {
    return {
      TAG: /* S */ 0,
      _0: add(n._0, m)
    };
  }
}

function mul(n, m) {
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    return /* O */ 0;
  } else {
    return add(m, mul(n._0, m));
  }
}

function sub(_n, _m) {
  while (true) {
    const m = _m;
    const n = _n;
    if (/* tag */ typeof n === "number" || typeof n === "string") {
      return n;
    }
    if (/* tag */ typeof m === "number" || typeof m === "string") {
      return n;
    }
    _m = m._0;
    _n = n._0;
    continue;
  };
}

function eqb(b1, b2) {
  if (b1 === /* True */ 0) {
    return b2;
  } else if (b2 === /* True */ 0) {
    return /* False */ 1;
  } else {
    return /* True */ 0;
  }
}

function add$1(n, m) {
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    return m;
  } else {
    return {
      TAG: /* S */ 0,
      _0: add$1(n._0, m)
    };
  }
}

function mul$1(n, m) {
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    return /* O */ 0;
  } else {
    return add$1(m, mul$1(n._0, m));
  }
}

function sub$1(_n, _m) {
  while (true) {
    const m = _m;
    const n = _n;
    if (/* tag */ typeof n === "number" || typeof n === "string") {
      return n;
    }
    if (/* tag */ typeof m === "number" || typeof m === "string") {
      return n;
    }
    _m = m._0;
    _n = n._0;
    continue;
  };
}

function eqb$1(_n, _m) {
  while (true) {
    const m = _m;
    const n = _n;
    if (/* tag */ typeof n === "number" || typeof n === "string") {
      if (/* tag */ typeof m === "number" || typeof m === "string") {
        return /* True */ 0;
      } else {
        return /* False */ 1;
      }
    }
    if (/* tag */ typeof m === "number" || typeof m === "string") {
      return /* False */ 1;
    }
    _m = m._0;
    _n = n._0;
    continue;
  };
}

function leb(_n, _m) {
  while (true) {
    const m = _m;
    const n = _n;
    if (/* tag */ typeof n === "number" || typeof n === "string") {
      return /* True */ 0;
    }
    if (/* tag */ typeof m === "number" || typeof m === "string") {
      return /* False */ 1;
    }
    _m = m._0;
    _n = n._0;
    continue;
  };
}

function ltb(n, m) {
  return leb({
    TAG: /* S */ 0,
    _0: n
  }, m);
}

function max(n, m) {
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    return m;
  } else if (/* tag */ typeof m === "number" || typeof m === "string") {
    return n;
  } else {
    return {
      TAG: /* S */ 0,
      _0: max(n._0, m._0)
    };
  }
}

function pow(n, param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return {
      TAG: /* S */ 0,
      _0: /* O */ 0
    };
  } else {
    return mul$1(n, pow(n, param._0));
  }
}

function divmod(_x, y, _q, _u) {
  while (true) {
    const u = _u;
    const q = _q;
    const x = _x;
    if (/* tag */ typeof x === "number" || typeof x === "string") {
      return {
        TAG: /* Pair */ 0,
        _0: q,
        _1: u
      };
    }
    const x$p = x._0;
    if (/* tag */ typeof u === "number" || typeof u === "string") {
      _u = y;
      _q = {
        TAG: /* S */ 0,
        _0: q
      };
      _x = x$p;
      continue;
    }
    _u = u._0;
    _x = x$p;
    continue;
  };
}

function div(x, y) {
  if (/* tag */ typeof y === "number" || typeof y === "string") {
    return y;
  }
  const y$p = y._0;
  return fst(divmod(x, y$p, /* O */ 0, y$p));
}

function modulo(x, param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return x;
  }
  const y$p = param._0;
  return sub$1(y$p, snd(divmod(x, y$p, /* O */ 0, y$p)));
}

const Nat = {
  add: add$1,
  mul: mul$1,
  sub: sub$1,
  eqb: eqb$1,
  leb: leb,
  ltb: ltb,
  max: max,
  pow: pow,
  divmod: divmod,
  div: div,
  modulo: modulo
};

function map(f, param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* Nil */ 0;
  } else {
    return {
      TAG: /* Cons */ 0,
      _0: Curry._1(f, param._0),
      _1: map(f, param._1)
    };
  }
}

function seq(start, param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* Nil */ 0;
  } else {
    return {
      TAG: /* Cons */ 0,
      _0: start,
      _1: seq({
        TAG: /* S */ 0,
        _0: start
      }, param._0)
    };
  }
}

function nth_error(_l, _param) {
  while (true) {
    const param = _param;
    const l = _l;
    if (/* tag */ typeof param === "number" || typeof param === "string") {
      if (/* tag */ typeof l === "number" || typeof l === "string") {
        return;
      } else {
        return Caml_option.some(l._0);
      }
    }
    if (/* tag */ typeof l === "number" || typeof l === "string") {
      return;
    }
    _param = param._0;
    _l = l._1;
    continue;
  };
}

function rev(param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* Nil */ 0;
  } else {
    return app(rev(param._1), {
      TAG: /* Cons */ 0,
      _0: param._0,
      _1: /* Nil */ 0
    });
  }
}

function flat_map(f, param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* Nil */ 0;
  } else {
    return app(Curry._1(f, param._0), flat_map(f, param._1));
  }
}

function fold_left(f, _l, _a0) {
  while (true) {
    const a0 = _a0;
    const l = _l;
    if (/* tag */ typeof l === "number" || typeof l === "string") {
      return a0;
    }
    _a0 = Curry._2(f, a0, l._0);
    _l = l._1;
    continue;
  };
}

function existsb(f, _param) {
  while (true) {
    const param = _param;
    if (/* tag */ typeof param === "number" || typeof param === "string") {
      return /* False */ 1;
    }
    const match = Curry._1(f, param._0);
    if (match === /* True */ 0) {
      return /* True */ 0;
    }
    _param = param._1;
    continue;
  };
}

function forallb(f, _param) {
  while (true) {
    const param = _param;
    if (/* tag */ typeof param === "number" || typeof param === "string") {
      return /* True */ 0;
    }
    const match = Curry._1(f, param._0);
    if (match !== /* True */ 0) {
      return /* False */ 1;
    }
    _param = param._1;
    continue;
  };
}

function filter(f, _param) {
  while (true) {
    const param = _param;
    if (/* tag */ typeof param === "number" || typeof param === "string") {
      return /* Nil */ 0;
    }
    const l0 = param._1;
    const x = param._0;
    const match = Curry._1(f, x);
    if (match === /* True */ 0) {
      return {
        TAG: /* Cons */ 0,
        _0: x,
        _1: filter(f, l0)
      };
    }
    _param = l0;
    continue;
  };
}

function find(f, _param) {
  while (true) {
    const param = _param;
    if (/* tag */ typeof param === "number" || typeof param === "string") {
      return;
    }
    const x = param._0;
    const match = Curry._1(f, x);
    if (match === /* True */ 0) {
      return Caml_option.some(x);
    }
    _param = param._1;
    continue;
  };
}

function combine(l, l$p) {
  if (/* tag */ typeof l === "number" || typeof l === "string" || /* tag */ typeof l$p === "number" || typeof l$p === "string") {
    return /* Nil */ 0;
  } else {
    return {
      TAG: /* Cons */ 0,
      _0: {
        TAG: /* Pair */ 0,
        _0: l._0,
        _1: l$p._0
      },
      _1: combine(l._1, l$p._1)
    };
  }
}

function eqb0(a, b) {
  const match = eqb(a._0, b._0);
  let match$1;
  match$1 = match === /* True */ 0 ? eqb(a._1, b._1) : /* False */ 1;
  let match$2;
  match$2 = match$1 === /* True */ 0 ? eqb(a._2, b._2) : /* False */ 1;
  let match$3;
  match$3 = match$2 === /* True */ 0 ? eqb(a._3, b._3) : /* False */ 1;
  let match$4;
  match$4 = match$3 === /* True */ 0 ? eqb(a._4, b._4) : /* False */ 1;
  let match$5;
  match$5 = match$4 === /* True */ 0 ? eqb(a._5, b._5) : /* False */ 1;
  let match$6;
  match$6 = match$5 === /* True */ 0 ? eqb(a._6, b._6) : /* False */ 1;
  if (match$6 === /* True */ 0) {
    return eqb(a._7, b._7);
  } else {
    return /* False */ 1;
  }
}

function eqb1(_s1, _s2) {
  while (true) {
    const s2 = _s2;
    const s1 = _s1;
    if (/* tag */ typeof s1 === "number" || typeof s1 === "string") {
      if (/* tag */ typeof s2 === "number" || typeof s2 === "string") {
        return /* True */ 0;
      } else {
        return /* False */ 1;
      }
    }
    if (/* tag */ typeof s2 === "number" || typeof s2 === "string") {
      return /* False */ 1;
    }
    const match = eqb0(s1._0, s2._0);
    if (match !== /* True */ 0) {
      return /* False */ 1;
    }
    _s2 = s2._1;
    _s1 = s1._1;
    continue;
  };
}

function append(s1, s2) {
  if (/* tag */ typeof s1 === "number" || typeof s1 === "string") {
    return s2;
  } else {
    return {
      TAG: /* String */ 0,
      _0: s1._0,
      _1: append(s1._1, s2)
    };
  }
}

function eqb$2(eqb2) {
  return eqb2;
}

function ci_col(c) {
  return c.ci_col;
}

function ci_color(c) {
  return c.ci_color;
}

function row_id(r) {
  return r.row_id;
}

function row_items(r) {
  return r.row_items;
}

function primary_items(p) {
  return p.primary_items;
}

function rows(p) {
  return p.rows;
}

function remove_primary(h, i, ps) {
  return filter((function (j) {
    return negb(Curry._2(h, j, i));
  }), ps);
}

function cell_on(h, i, r) {
  return find((function (ci) {
    return Curry._2(h, ci.ci_col, i);
  }), r.row_items);
}

function row_has_col(h, i, r) {
  const match = cell_on(h, i, r);
  if (match !== undefined) {
    return /* True */ 0;
  } else {
    return /* False */ 1;
  }
}

function rows_with_col(h, i, rs) {
  return filter((function (param) {
    return row_has_col(h, i, param);
  }), rs);
}

function col_len(h, i, p) {
  return length(rows_with_col(h, i, p.rows));
}

function cover(h, i, p) {
  return {
    primary_items: remove_primary(h, i, p.primary_items),
    rows: filter((function (r) {
      return negb(row_has_col(h, i, r));
    }), p.rows)
  };
}

function row_color_ok(h, h0, i, x, r) {
  const ci = cell_on(h, i, r);
  if (ci === undefined) {
    return /* True */ 0;
  }
  const y = ci.ci_color;
  if (y !== undefined) {
    return Curry._2(h0, Caml_option.valFromOption(y), x);
  } else {
    return /* False */ 1;
  }
}

function purify(h, h0, i, x, p) {
  return {
    primary_items: p.primary_items,
    rows: filter((function (param) {
      return row_color_ok(h, h0, i, x, param);
    }), p.rows)
  };
}

function commit_cell(h, h0, ci, p) {
  const x = ci.ci_color;
  if (x !== undefined) {
    return purify(h, h0, ci.ci_col, Caml_option.valFromOption(x), p);
  } else {
    return cover(h, ci.ci_col, p);
  }
}

function commit_other_cell(h, h0, chosen_col, ci, p) {
  const match = Curry._2(h, ci.ci_col, chosen_col);
  if (match === /* True */ 0) {
    return p;
  } else {
    return commit_cell(h, h0, ci, p);
  }
}

function commit(h, h0, chosen_col, chosen_row, p) {
  return fold_left((function (acc, ci) {
    return commit_other_cell(h, h0, chosen_col, ci, acc);
  }), chosen_row.row_items, cover(h, chosen_col, p));
}

function choose_col_aux(h, p, _best, _best_len, _param) {
  while (true) {
    const param = _param;
    const best_len = _best_len;
    const best = _best;
    if (/* tag */ typeof param === "number" || typeof param === "string") {
      return best;
    }
    const rest$p = param._1;
    const i = param._0;
    const n = col_len(h, i, p);
    const match = leb({
      TAG: /* S */ 0,
      _0: n
    }, best_len);
    if (match === /* True */ 0) {
      _param = rest$p;
      _best_len = n;
      _best = i;
      continue;
    }
    _param = rest$p;
    continue;
  };
}

function choose_col(h, p) {
  const match = p.primary_items;
  if (/* tag */ typeof match === "number" || typeof match === "string") {
    return;
  }
  const i = match._0;
  return Caml_option.some(choose_col_aux(h, p, i, col_len(h, i, p), match._1));
}

function search(h, h0, fuel, p) {
  if (/* tag */ typeof fuel === "number" || typeof fuel === "string") {
    return /* Nil */ 0;
  }
  const fuel$p = fuel._0;
  const match = p.primary_items;
  if (/* tag */ typeof match === "number" || typeof match === "string") {
    return {
      TAG: /* Cons */ 0,
      _0: /* Nil */ 0,
      _1: /* Nil */ 0
    };
  }
  const c = choose_col(h, p);
  if (c === undefined) {
    return {
      TAG: /* Cons */ 0,
      _0: /* Nil */ 0,
      _1: /* Nil */ 0
    };
  }
  const c$1 = Caml_option.valFromOption(c);
  return flat_map((function (r) {
    return map((function (sol) {
      return {
        TAG: /* Cons */ 0,
        _0: r,
        _1: sol
      };
    }), search(h, h0, fuel$p, commit(h, h0, c$1, r, p)));
  }), rows_with_col(h, c$1, p.rows));
}

function solution_row_ids(sol) {
  return map((function (r) {
    return r.row_id;
  }), sol);
}

function solve_ids(h, h0, fuel, p) {
  return map(solution_row_ids, search(h, h0, fuel, p));
}

const GDance = {
  eqb: eqb$2,
  coq_Eqb_nat: eqb$1,
  coq_Eqb_string: eqb1,
  ci_col: ci_col,
  ci_color: ci_color,
  row_id: row_id,
  row_items: row_items,
  primary_items: primary_items,
  rows: rows,
  remove_primary: remove_primary,
  cell_on: cell_on,
  row_has_col: row_has_col,
  rows_with_col: rows_with_col,
  col_len: col_len,
  cover: cover,
  row_color_ok: row_color_ok,
  purify: purify,
  commit_cell: commit_cell,
  commit_other_cell: commit_other_cell,
  commit: commit,
  choose_col_aux: choose_col_aux,
  choose_col: choose_col,
  search: search,
  solve: search,
  solution_row_ids: solution_row_ids,
  solve_ids: solve_ids
};

function gcol_eqb(a, b) {
  switch (a.TAG) {
    case /* Cell */ 0 :
      if (b.TAG !== /* Cell */ 0) {
        return /* False */ 1;
      }
      const match = eqb$1(a._0, b._0);
      if (match === /* True */ 0) {
        return eqb$1(a._1, b._1);
      } else {
        return /* False */ 1;
      }
    case /* RowSym */ 1 :
      if (b.TAG !== /* RowSym */ 1) {
        return /* False */ 1;
      }
      const match$1 = eqb$1(a._0, b._0);
      if (match$1 === /* True */ 0) {
        return eqb$1(a._1, b._1);
      } else {
        return /* False */ 1;
      }
    case /* ColSym */ 2 :
      if (b.TAG !== /* ColSym */ 2) {
        return /* False */ 1;
      }
      const match$2 = eqb$1(a._0, b._0);
      if (match$2 === /* True */ 0) {
        return eqb$1(a._1, b._1);
      } else {
        return /* False */ 1;
      }
    case /* BoxSym */ 3 :
      if (b.TAG !== /* BoxSym */ 3) {
        return /* False */ 1;
      }
      const match$3 = eqb$1(a._0, b._0);
      let match$4;
      match$4 = match$3 === /* True */ 0 ? eqb$1(a._1, b._1) : /* False */ 1;
      if (match$4 === /* True */ 0) {
        return eqb$1(a._2, b._2);
      } else {
        return /* False */ 1;
      }
  }
}

function su(x) {
  return {
    ci_col: x,
    ci_color: undefined
  };
}

function max3(a, b, c) {
  return max(a, max(b, c));
}

function alphabet_size(r, c, r0, c0) {
  return max3(mul(r, r0), mul(c, c0), mul(r0, c0));
}

function row_indices(r, r0) {
  return seq(/* O */ 0, mul(r, r0));
}

function col_indices(c, c0) {
  return seq(/* O */ 0, mul(c, c0));
}

function symbols(r, c, r0, c0) {
  return seq(/* O */ 0, alphabet_size(r, c, r0, c0));
}

function box_row_of(r, row0) {
  return div(row0, r);
}

function box_col_of(c, col) {
  return div(col, c);
}

function candidate_id(r, c, r0, c0, row0, col, sym) {
  return add(mul(add(mul(row0, mul(c, c0)), col), alphabet_size(r, c, r0, c0)), sym);
}

function candidate_items(param, param$1, r, c, row0, col, sym) {
  return {
    TAG: /* Cons */ 0,
    _0: {
      TAG: /* Cell */ 0,
      _0: row0,
      _1: col
    },
    _1: {
      TAG: /* Cons */ 0,
      _0: {
        TAG: /* RowSym */ 1,
        _0: row0,
        _1: sym
      },
      _1: {
        TAG: /* Cons */ 0,
        _0: {
          TAG: /* ColSym */ 2,
          _0: col,
          _1: sym
        },
        _1: {
          TAG: /* Cons */ 0,
          _0: {
            TAG: /* BoxSym */ 3,
            _0: div(row0, r),
            _1: div(col, c),
            _2: sym
          },
          _1: /* Nil */ 0
        }
      }
    }
  };
}

function candidate_row(r, c, r0, c0, row_ix, col_ix, sym) {
  return {
    row_id: candidate_id(r, c, r0, c0, row_ix, col_ix, sym),
    row_items: map(su, candidate_items(r, c, r0, c0, row_ix, col_ix, sym))
  };
}

function all_cells(r, c, r0, c0) {
  return flat_map((function (row0) {
    return map((function (col) {
      return {
        TAG: /* Cell */ 0,
        _0: row0,
        _1: col
      };
    }), col_indices(c, c0));
  }), row_indices(r, r0));
}

function all_row_symbol_constraints(r, c, r0, c0) {
  return flat_map((function (row0) {
    return map((function (sym) {
      return {
        TAG: /* RowSym */ 1,
        _0: row0,
        _1: sym
      };
    }), symbols(r, c, r0, c0));
  }), row_indices(r, r0));
}

function all_col_symbol_constraints(r, c, r0, c0) {
  return flat_map((function (col) {
    return map((function (sym) {
      return {
        TAG: /* ColSym */ 2,
        _0: col,
        _1: sym
      };
    }), symbols(r, c, r0, c0));
  }), col_indices(c, c0));
}

function all_box_symbol_constraints(r, c, r0, c0) {
  return flat_map((function (br) {
    return flat_map((function (bc) {
      return map((function (sym) {
        return {
          TAG: /* BoxSym */ 3,
          _0: br,
          _1: bc,
          _2: sym
        };
      }), symbols(r, c, r0, c0));
    }), seq(/* O */ 0, c));
  }), seq(/* O */ 0, r));
}

function all_sudoku_constraints(r, c, r0, c0) {
  return app(all_cells(r, c, r0, c0), app(all_row_symbol_constraints(r, c, r0, c0), app(all_col_symbol_constraints(r, c, r0, c0), all_box_symbol_constraints(r, c, r0, c0))));
}

function all_candidate_rows(r, c, r0, c0) {
  return flat_map((function (row0) {
    return flat_map((function (col) {
      return map((function (sym) {
        return candidate_row(r, c, r0, c0, row0, col, sym);
      }), symbols(r, c, r0, c0));
    }), col_indices(c, c0));
  }), row_indices(r, r0));
}

function generalized_sudoku_problem_at_most(r, c, r0, c0) {
  return {
    primary_items: all_cells(r, c, r0, c0),
    rows: all_candidate_rows(r, c, r0, c0)
  };
}

function generalized_sudoku_problem_exact(r, c, r0, c0) {
  return {
    primary_items: all_sudoku_constraints(r, c, r0, c0),
    rows: all_candidate_rows(r, c, r0, c0)
  };
}

const SudokuProblem = {
  gcol_eqb: gcol_eqb,
  coq_Eqb_GCol: gcol_eqb,
  su: su,
  rows_count: mul,
  cols_count: mul,
  box_size: mul,
  max3: max3,
  alphabet_size: alphabet_size,
  row_indices: row_indices,
  col_indices: col_indices,
  symbols: symbols,
  box_row_of: box_row_of,
  box_col_of: box_col_of,
  candidate_id: candidate_id,
  candidate_items: candidate_items,
  candidate_row: candidate_row,
  all_cells: all_cells,
  all_row_symbol_constraints: all_row_symbol_constraints,
  all_col_symbol_constraints: all_col_symbol_constraints,
  all_box_symbol_constraints: all_box_symbol_constraints,
  all_sudoku_constraints: all_sudoku_constraints,
  all_candidate_rows: all_candidate_rows,
  generalized_sudoku_problem_at_most: generalized_sudoku_problem_at_most,
  generalized_sudoku_problem_exact: generalized_sudoku_problem_exact
};

function ascii_of_digit(param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return {
      TAG: /* Ascii */ 0,
      _0: /* False */ 1,
      _1: /* False */ 1,
      _2: /* False */ 1,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* False */ 1,
      _7: /* False */ 1
    };
  }
  const n = param._0;
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    return {
      TAG: /* Ascii */ 0,
      _0: /* True */ 0,
      _1: /* False */ 1,
      _2: /* False */ 1,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* False */ 1,
      _7: /* False */ 1
    };
  }
  const n0 = n._0;
  if (/* tag */ typeof n0 === "number" || typeof n0 === "string") {
    return {
      TAG: /* Ascii */ 0,
      _0: /* False */ 1,
      _1: /* True */ 0,
      _2: /* False */ 1,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* False */ 1,
      _7: /* False */ 1
    };
  }
  const n1 = n0._0;
  if (/* tag */ typeof n1 === "number" || typeof n1 === "string") {
    return {
      TAG: /* Ascii */ 0,
      _0: /* True */ 0,
      _1: /* True */ 0,
      _2: /* False */ 1,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* False */ 1,
      _7: /* False */ 1
    };
  }
  const n2 = n1._0;
  if (/* tag */ typeof n2 === "number" || typeof n2 === "string") {
    return {
      TAG: /* Ascii */ 0,
      _0: /* False */ 1,
      _1: /* False */ 1,
      _2: /* True */ 0,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* False */ 1,
      _7: /* False */ 1
    };
  }
  const n3 = n2._0;
  if (/* tag */ typeof n3 === "number" || typeof n3 === "string") {
    return {
      TAG: /* Ascii */ 0,
      _0: /* True */ 0,
      _1: /* False */ 1,
      _2: /* True */ 0,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* False */ 1,
      _7: /* False */ 1
    };
  }
  const n4 = n3._0;
  if (/* tag */ typeof n4 === "number" || typeof n4 === "string") {
    return {
      TAG: /* Ascii */ 0,
      _0: /* False */ 1,
      _1: /* True */ 0,
      _2: /* True */ 0,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* False */ 1,
      _7: /* False */ 1
    };
  }
  const n5 = n4._0;
  if (/* tag */ typeof n5 === "number" || typeof n5 === "string") {
    return {
      TAG: /* Ascii */ 0,
      _0: /* True */ 0,
      _1: /* True */ 0,
      _2: /* True */ 0,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* False */ 1,
      _7: /* False */ 1
    };
  }
  let tmp = n5._0;
  if (/* tag */ typeof tmp === "number" || typeof tmp === "string") {
    return {
      TAG: /* Ascii */ 0,
      _0: /* False */ 1,
      _1: /* False */ 1,
      _2: /* False */ 1,
      _3: /* True */ 0,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* False */ 1,
      _7: /* False */ 1
    };
  } else {
    return {
      TAG: /* Ascii */ 0,
      _0: /* True */ 0,
      _1: /* False */ 1,
      _2: /* False */ 1,
      _3: /* True */ 0,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* False */ 1,
      _7: /* False */ 1
    };
  }
}

function digits_rev_fuel(fuel, n) {
  if (/* tag */ typeof fuel === "number" || typeof fuel === "string") {
    return /* Nil */ 0;
  }
  const d = modulo(n, {
    TAG: /* S */ 0,
    _0: {
      TAG: /* S */ 0,
      _0: {
        TAG: /* S */ 0,
        _0: {
          TAG: /* S */ 0,
          _0: {
            TAG: /* S */ 0,
            _0: {
              TAG: /* S */ 0,
              _0: {
                TAG: /* S */ 0,
                _0: {
                  TAG: /* S */ 0,
                  _0: {
                    TAG: /* S */ 0,
                    _0: {
                      TAG: /* S */ 0,
                      _0: /* O */ 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  });
  const match = leb({
    TAG: /* S */ 0,
    _0: n
  }, {
    TAG: /* S */ 0,
    _0: {
      TAG: /* S */ 0,
      _0: {
        TAG: /* S */ 0,
        _0: {
          TAG: /* S */ 0,
          _0: {
            TAG: /* S */ 0,
            _0: {
              TAG: /* S */ 0,
              _0: {
                TAG: /* S */ 0,
                _0: {
                  TAG: /* S */ 0,
                  _0: {
                    TAG: /* S */ 0,
                    _0: {
                      TAG: /* S */ 0,
                      _0: /* O */ 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  });
  if (match === /* True */ 0) {
    return {
      TAG: /* Cons */ 0,
      _0: d,
      _1: /* Nil */ 0
    };
  } else {
    return {
      TAG: /* Cons */ 0,
      _0: d,
      _1: digits_rev_fuel(fuel._0, div(n, {
        TAG: /* S */ 0,
        _0: {
          TAG: /* S */ 0,
          _0: {
            TAG: /* S */ 0,
            _0: {
              TAG: /* S */ 0,
              _0: {
                TAG: /* S */ 0,
                _0: {
                  TAG: /* S */ 0,
                  _0: {
                    TAG: /* S */ 0,
                    _0: {
                      TAG: /* S */ 0,
                      _0: {
                        TAG: /* S */ 0,
                        _0: {
                          TAG: /* S */ 0,
                          _0: /* O */ 0
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }))
    };
  }
}

function string_of_ascii_list(param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* EmptyString */ 0;
  } else {
    return {
      TAG: /* String */ 0,
      _0: param._0,
      _1: string_of_ascii_list(param._1)
    };
  }
}

function nat_to_string(n) {
  return string_of_ascii_list(map(ascii_of_digit, rev(digits_rev_fuel({
    TAG: /* S */ 0,
    _0: n
  }, n))));
}

function label(prefix, i) {
  return append(prefix, nat_to_string({
    TAG: /* S */ 0,
    _0: i
  }));
}

function generated_names(prefix, n) {
  return map((function (param) {
    return label(prefix, param);
  }), seq(/* O */ 0, n));
}

function indexed(xs) {
  return combine(seq(/* O */ 0, length(xs)), xs);
}

function choose_color(colors, i) {
  const n = length(colors);
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    return;
  } else {
    return nth_error(colors, modulo(i, {
      TAG: /* S */ 0,
      _0: n._0
    }));
  }
}

function primary_item_citem(item0) {
  return {
    ci_col: item0,
    ci_color: undefined
  };
}

function secondary_source_citem(src, source_color) {
  return {
    ci_col: src,
    ci_color: source_color
  };
}

function warehouse_row(id, src, items, param, source_color) {
  return {
    row_id: id,
    row_items: app(map(primary_item_citem, items), {
      TAG: /* Cons */ 0,
      _0: {
        ci_col: src,
        ci_color: source_color
      },
      _1: /* Nil */ 0
    })
  };
}

function assigned_items_for_source_shifted(items, n_sources, witness_id, source_id) {
  return map(snd, filter((function (pat) {
    return eqb$1(modulo(add(pat._0, witness_id), n_sources), source_id);
  }), indexed(items)));
}

function guaranteed_row_id(n_sources, witness_id, source_id) {
  return add(mul(witness_id, n_sources), source_id);
}

function guaranteed_rows_for_witness(items, sources, witness_id) {
  return map((function (pat) {
    const si = pat._0;
    return warehouse_row(guaranteed_row_id(length(sources), witness_id, si), pat._1, assigned_items_for_source_shifted(items, length(sources), witness_id, si), undefined, undefined);
  }), indexed(sources));
}

function guaranteed_k_rows(items, sources, k) {
  return flat_map((function (witness_id) {
    return guaranteed_rows_for_witness(items, sources, witness_id);
  }), seq(/* O */ 0, k));
}

function guaranteed_k_problem(n_items, n_sources, k) {
  const items = generated_names({
    TAG: /* String */ 0,
    _0: {
      TAG: /* Ascii */ 0,
      _0: /* True */ 0,
      _1: /* False */ 1,
      _2: /* False */ 1,
      _3: /* True */ 0,
      _4: /* False */ 1,
      _5: /* True */ 0,
      _6: /* True */ 0,
      _7: /* False */ 1
    },
    _1: {
      TAG: /* String */ 0,
      _0: {
        TAG: /* Ascii */ 0,
        _0: /* False */ 1,
        _1: /* False */ 1,
        _2: /* True */ 0,
        _3: /* False */ 1,
        _4: /* True */ 0,
        _5: /* True */ 0,
        _6: /* True */ 0,
        _7: /* False */ 1
      },
      _1: {
        TAG: /* String */ 0,
        _0: {
          TAG: /* Ascii */ 0,
          _0: /* True */ 0,
          _1: /* False */ 1,
          _2: /* True */ 0,
          _3: /* False */ 1,
          _4: /* False */ 1,
          _5: /* True */ 0,
          _6: /* True */ 0,
          _7: /* False */ 1
        },
        _1: {
          TAG: /* String */ 0,
          _0: {
            TAG: /* Ascii */ 0,
            _0: /* True */ 0,
            _1: /* False */ 1,
            _2: /* True */ 0,
            _3: /* True */ 0,
            _4: /* False */ 1,
            _5: /* True */ 0,
            _6: /* True */ 0,
            _7: /* False */ 1
          },
          _1: /* EmptyString */ 0
        }
      }
    }
  }, n_items);
  const sources = generated_names({
    TAG: /* String */ 0,
    _0: {
      TAG: /* Ascii */ 0,
      _0: /* True */ 0,
      _1: /* True */ 0,
      _2: /* False */ 1,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* True */ 0,
      _7: /* False */ 1
    },
    _1: {
      TAG: /* String */ 0,
      _0: {
        TAG: /* Ascii */ 0,
        _0: /* False */ 1,
        _1: /* True */ 0,
        _2: /* False */ 1,
        _3: /* False */ 1,
        _4: /* True */ 0,
        _5: /* True */ 0,
        _6: /* True */ 0,
        _7: /* False */ 1
      },
      _1: {
        TAG: /* String */ 0,
        _0: {
          TAG: /* Ascii */ 0,
          _0: /* True */ 0,
          _1: /* True */ 0,
          _2: /* False */ 1,
          _3: /* False */ 1,
          _4: /* False */ 1,
          _5: /* True */ 0,
          _6: /* True */ 0,
          _7: /* False */ 1
        },
        _1: /* EmptyString */ 0
      }
    }
  }, n_sources);
  return {
    primary_items: items,
    rows: guaranteed_k_rows(items, sources, k)
  };
}

function guaranteed_rows_for_witness_colored(items, sources, product_colors, source_reqs, witness_id) {
  return map((function (pat) {
    const si = pat._0;
    const product_color = choose_color(product_colors, add(witness_id, si));
    const source_color = choose_color(source_reqs, si);
    return warehouse_row(guaranteed_row_id(length(sources), witness_id, si), pat._1, assigned_items_for_source_shifted(items, length(sources), witness_id, si), product_color, source_color);
  }), indexed(sources));
}

function guaranteed_k_colored_rows(items, sources, product_colors, source_reqs, k) {
  return flat_map((function (witness_id) {
    return guaranteed_rows_for_witness_colored(items, sources, product_colors, source_reqs, witness_id);
  }), seq(/* O */ 0, k));
}

function guaranteed_k_colored_problem(n_items, n_sources, n_product_colors, n_source_reqs, k) {
  const items = generated_names({
    TAG: /* String */ 0,
    _0: {
      TAG: /* Ascii */ 0,
      _0: /* True */ 0,
      _1: /* False */ 1,
      _2: /* False */ 1,
      _3: /* True */ 0,
      _4: /* False */ 1,
      _5: /* True */ 0,
      _6: /* True */ 0,
      _7: /* False */ 1
    },
    _1: {
      TAG: /* String */ 0,
      _0: {
        TAG: /* Ascii */ 0,
        _0: /* False */ 1,
        _1: /* False */ 1,
        _2: /* True */ 0,
        _3: /* False */ 1,
        _4: /* True */ 0,
        _5: /* True */ 0,
        _6: /* True */ 0,
        _7: /* False */ 1
      },
      _1: {
        TAG: /* String */ 0,
        _0: {
          TAG: /* Ascii */ 0,
          _0: /* True */ 0,
          _1: /* False */ 1,
          _2: /* True */ 0,
          _3: /* False */ 1,
          _4: /* False */ 1,
          _5: /* True */ 0,
          _6: /* True */ 0,
          _7: /* False */ 1
        },
        _1: {
          TAG: /* String */ 0,
          _0: {
            TAG: /* Ascii */ 0,
            _0: /* True */ 0,
            _1: /* False */ 1,
            _2: /* True */ 0,
            _3: /* True */ 0,
            _4: /* False */ 1,
            _5: /* True */ 0,
            _6: /* True */ 0,
            _7: /* False */ 1
          },
          _1: /* EmptyString */ 0
        }
      }
    }
  }, n_items);
  const sources = generated_names({
    TAG: /* String */ 0,
    _0: {
      TAG: /* Ascii */ 0,
      _0: /* True */ 0,
      _1: /* True */ 0,
      _2: /* False */ 1,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* True */ 0,
      _7: /* False */ 1
    },
    _1: {
      TAG: /* String */ 0,
      _0: {
        TAG: /* Ascii */ 0,
        _0: /* False */ 1,
        _1: /* True */ 0,
        _2: /* False */ 1,
        _3: /* False */ 1,
        _4: /* True */ 0,
        _5: /* True */ 0,
        _6: /* True */ 0,
        _7: /* False */ 1
      },
      _1: {
        TAG: /* String */ 0,
        _0: {
          TAG: /* Ascii */ 0,
          _0: /* True */ 0,
          _1: /* True */ 0,
          _2: /* False */ 1,
          _3: /* False */ 1,
          _4: /* False */ 1,
          _5: /* True */ 0,
          _6: /* True */ 0,
          _7: /* False */ 1
        },
        _1: /* EmptyString */ 0
      }
    }
  }, n_sources);
  const product_colors = generated_names({
    TAG: /* String */ 0,
    _0: {
      TAG: /* Ascii */ 0,
      _0: /* True */ 0,
      _1: /* True */ 0,
      _2: /* False */ 1,
      _3: /* False */ 1,
      _4: /* False */ 1,
      _5: /* True */ 0,
      _6: /* True */ 0,
      _7: /* False */ 1
    },
    _1: {
      TAG: /* String */ 0,
      _0: {
        TAG: /* Ascii */ 0,
        _0: /* True */ 0,
        _1: /* True */ 0,
        _2: /* True */ 0,
        _3: /* True */ 0,
        _4: /* False */ 1,
        _5: /* True */ 0,
        _6: /* True */ 0,
        _7: /* False */ 1
      },
      _1: {
        TAG: /* String */ 0,
        _0: {
          TAG: /* Ascii */ 0,
          _0: /* False */ 1,
          _1: /* False */ 1,
          _2: /* True */ 0,
          _3: /* True */ 0,
          _4: /* False */ 1,
          _5: /* True */ 0,
          _6: /* True */ 0,
          _7: /* False */ 1
        },
        _1: {
          TAG: /* String */ 0,
          _0: {
            TAG: /* Ascii */ 0,
            _0: /* True */ 0,
            _1: /* True */ 0,
            _2: /* True */ 0,
            _3: /* True */ 0,
            _4: /* False */ 1,
            _5: /* True */ 0,
            _6: /* True */ 0,
            _7: /* False */ 1
          },
          _1: {
            TAG: /* String */ 0,
            _0: {
              TAG: /* Ascii */ 0,
              _0: /* False */ 1,
              _1: /* True */ 0,
              _2: /* False */ 1,
              _3: /* False */ 1,
              _4: /* True */ 0,
              _5: /* True */ 0,
              _6: /* True */ 0,
              _7: /* False */ 1
            },
            _1: /* EmptyString */ 0
          }
        }
      }
    }
  }, n_product_colors);
  const source_reqs = generated_names({
    TAG: /* String */ 0,
    _0: {
      TAG: /* Ascii */ 0,
      _0: /* False */ 1,
      _1: /* True */ 0,
      _2: /* False */ 1,
      _3: /* False */ 1,
      _4: /* True */ 0,
      _5: /* True */ 0,
      _6: /* True */ 0,
      _7: /* False */ 1
    },
    _1: {
      TAG: /* String */ 0,
      _0: {
        TAG: /* Ascii */ 0,
        _0: /* True */ 0,
        _1: /* False */ 1,
        _2: /* True */ 0,
        _3: /* False */ 1,
        _4: /* False */ 1,
        _5: /* True */ 0,
        _6: /* True */ 0,
        _7: /* False */ 1
      },
      _1: {
        TAG: /* String */ 0,
        _0: {
          TAG: /* Ascii */ 0,
          _0: /* True */ 0,
          _1: /* False */ 1,
          _2: /* False */ 1,
          _3: /* False */ 1,
          _4: /* True */ 0,
          _5: /* True */ 0,
          _6: /* True */ 0,
          _7: /* False */ 1
        },
        _1: /* EmptyString */ 0
      }
    }
  }, n_source_reqs);
  return {
    primary_items: items,
    rows: guaranteed_k_colored_rows(items, sources, product_colors, source_reqs, k)
  };
}

const Guaranteed_K_Warehouse = {
  ascii_of_digit: ascii_of_digit,
  digits_rev_fuel: digits_rev_fuel,
  string_of_ascii_list: string_of_ascii_list,
  nat_to_string: nat_to_string,
  label: label,
  generated_names: generated_names,
  indexed: indexed,
  nth_option: nth_error,
  choose_color: choose_color,
  primary_item_citem: primary_item_citem,
  secondary_source_citem: secondary_source_citem,
  warehouse_row: warehouse_row,
  assigned_items_for_source_shifted: assigned_items_for_source_shifted,
  guaranteed_row_id: guaranteed_row_id,
  guaranteed_rows_for_witness: guaranteed_rows_for_witness,
  guaranteed_k_rows: guaranteed_k_rows,
  guaranteed_k_problem: guaranteed_k_problem,
  guaranteed_rows_for_witness_colored: guaranteed_rows_for_witness_colored,
  guaranteed_k_colored_rows: guaranteed_k_colored_rows,
  guaranteed_k_colored_problem: guaranteed_k_colored_problem
};

function ccol_eqb(a, b) {
  if (/* tag */ typeof a === "number" || typeof a === "string") {
    if (/* tag */ typeof b === "number" || typeof b === "string") {
      return /* True */ 0;
    } else {
      return /* False */ 1;
    }
  }
  switch (a.TAG) {
    case /* Slot */ 0 :
      if (/* tag */ typeof b === "number" || typeof b === "string" || b.TAG !== /* Slot */ 0) {
        return /* False */ 1;
      } else {
        return eqb$1(a._0, b._0);
      }
    case /* Value */ 1 :
      if (/* tag */ typeof b === "number" || typeof b === "string" || b.TAG !== /* Value */ 1) {
        return /* False */ 1;
      } else {
        return eqb$1(a._0, b._0);
      }
    case /* Occur */ 2 :
      if (/* tag */ typeof b === "number" || typeof b === "string" || b.TAG !== /* Occur */ 2) {
        return /* False */ 1;
      } else {
        return eqb$1(a._0, b._0);
      }
    case /* PartAt */ 3 :
      if (/* tag */ typeof b === "number" || typeof b === "string") {
        return /* False */ 1;
      }
      if (b.TAG !== /* PartAt */ 3) {
        return /* False */ 1;
      }
      const match = eqb$1(a._0, b._0);
      if (match === /* True */ 0) {
        return eqb$1(a._1, b._1);
      } else {
        return /* False */ 1;
      }
    case /* QRow */ 4 :
      if (/* tag */ typeof b === "number" || typeof b === "string" || b.TAG !== /* QRow */ 4) {
        return /* False */ 1;
      } else {
        return eqb$1(a._0, b._0);
      }
    case /* QCol */ 5 :
      if (/* tag */ typeof b === "number" || typeof b === "string" || b.TAG !== /* QCol */ 5) {
        return /* False */ 1;
      } else {
        return eqb$1(a._0, b._0);
      }
    case /* QDiag1 */ 6 :
      if (/* tag */ typeof b === "number" || typeof b === "string" || b.TAG !== /* QDiag1 */ 6) {
        return /* False */ 1;
      } else {
        return eqb$1(a._0, b._0);
      }
    case /* QDiag2 */ 7 :
      if (/* tag */ typeof b === "number" || typeof b === "string" || b.TAG !== /* QDiag2 */ 7) {
        return /* False */ 1;
      } else {
        return eqb$1(a._0, b._0);
      }
  }
}

function item(c) {
  return {
    ci_col: c,
    ci_color: undefined
  };
}

function make_row(id, cols) {
  return {
    row_id: id,
    row_items: map(item, cols)
  };
}

function make_problem(primary, rows0) {
  return {
    primary_items: primary,
    rows: rows0
  };
}

function slots(k) {
  return map((function (x) {
    return {
      TAG: /* Slot */ 0,
      _0: x
    };
  }), seq(/* O */ 0, k));
}

function occurs(n) {
  return map((function (x) {
    return {
      TAG: /* Occur */ 2,
      _0: x
    };
  }), seq(/* O */ 0, n));
}

function assignment_id(n, slot, value) {
  return add(mul(slot, n), value);
}

function tuple_row(n, slot, value) {
  return make_row(assignment_id(n, slot, value), {
    TAG: /* Cons */ 0,
    _0: {
      TAG: /* Slot */ 0,
      _0: slot
    },
    _1: /* Nil */ 0
  });
}

function assignment_rows_tuple(k, n) {
  return flat_map((function (s) {
    return map((function (v) {
      return tuple_row(n, s, v);
    }), seq(/* O */ 0, n));
  }), seq(/* O */ 0, k));
}

function tuple_problem(k, n) {
  return {
    primary_items: slots(k),
    rows: assignment_rows_tuple(k, n)
  };
}

function permutation_row(n, slot, value) {
  return make_row(assignment_id(n, slot, value), {
    TAG: /* Cons */ 0,
    _0: {
      TAG: /* Slot */ 0,
      _0: slot
    },
    _1: {
      TAG: /* Cons */ 0,
      _0: {
        TAG: /* Value */ 1,
        _0: value
      },
      _1: /* Nil */ 0
    }
  });
}

function assignment_rows_permutation(k, n) {
  return flat_map((function (s) {
    return map((function (v) {
      return permutation_row(n, s, v);
    }), seq(/* O */ 0, n));
  }), seq(/* O */ 0, k));
}

function permutation_problem(k, n) {
  return {
    primary_items: slots(k),
    rows: assignment_rows_permutation(k, n)
  };
}

function combinations_from(k, start, n) {
  if (/* tag */ typeof k === "number" || typeof k === "string") {
    return {
      TAG: /* Cons */ 0,
      _0: /* Nil */ 0,
      _1: /* Nil */ 0
    };
  }
  const k$p = k._0;
  return flat_map((function (v) {
    return map((function (rest) {
      return {
        TAG: /* Cons */ 0,
        _0: v,
        _1: rest
      };
    }), combinations_from(k$p, {
      TAG: /* S */ 0,
      _0: v
    }, n));
  }), seq(start, sub(n, start)));
}

function combinations(k, n) {
  return combinations_from(k, /* O */ 0, n);
}

function combination_cols_aux(slot, param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* Nil */ 0;
  } else {
    return {
      TAG: /* Cons */ 0,
      _0: {
        TAG: /* Slot */ 0,
        _0: slot
      },
      _1: {
        TAG: /* Cons */ 0,
        _0: {
          TAG: /* Value */ 1,
          _0: param._0
        },
        _1: combination_cols_aux({
          TAG: /* S */ 0,
          _0: slot
        }, param._1)
      }
    };
  }
}

function combination_row(id, xs) {
  return make_row(id, {
    TAG: /* Cons */ 0,
    _0: /* PickOne */ 0,
    _1: combination_cols_aux(/* O */ 0, xs)
  });
}

function indexed$1(xs) {
  return combine(seq(/* O */ 0, length(xs)), xs);
}

function combination_problem(k, n) {
  return {
    primary_items: {
      TAG: /* Cons */ 0,
      _0: /* PickOne */ 0,
      _1: /* Nil */ 0
    },
    rows: map((function (pat) {
      return combination_row(pat._0, pat._1);
    }), indexed$1(combinations_from(k, /* O */ 0, n)))
  };
}

function sum_nat(param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* O */ 0;
  } else {
    return add(param._0, sum_nat(param._1));
  }
}

function nonincreasing_from(_prev, _param) {
  while (true) {
    const param = _param;
    const prev = _prev;
    if (/* tag */ typeof param === "number" || typeof param === "string") {
      return /* True */ 0;
    }
    const x = param._0;
    const match = leb(x, prev);
    if (match !== /* True */ 0) {
      return /* False */ 1;
    }
    _param = param._1;
    _prev = x;
    continue;
  };
}

function nonincreasing(param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* True */ 0;
  } else {
    return nonincreasing_from(param._0, param._1);
  }
}

function is_partition_of(n, xs) {
  const match = eqb$1(sum_nat(xs), n);
  if (match === /* True */ 0) {
    return nonincreasing(xs);
  } else {
    return /* False */ 1;
  }
}

function partitions_bounded(fuel, n, max_part) {
  if (/* tag */ typeof fuel === "number" || typeof fuel === "string") {
    return /* Nil */ 0;
  }
  const fuel$p = fuel._0;
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    return {
      TAG: /* Cons */ 0,
      _0: /* Nil */ 0,
      _1: /* Nil */ 0
    };
  } else {
    return flat_map((function (x) {
      return map((function (rest) {
        return {
          TAG: /* Cons */ 0,
          _0: x,
          _1: rest
        };
      }), partitions_bounded(fuel$p, sub(n, x), x));
    }), seq({
      TAG: /* S */ 0,
      _0: /* O */ 0
    }, max_part));
  }
}

function partitions_of(n) {
  return filter((function (param) {
    return is_partition_of(n, param);
  }), partitions_bounded({
    TAG: /* S */ 0,
    _0: n
  }, n, n));
}

function partition_cols_aux(i, param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* Nil */ 0;
  } else {
    return {
      TAG: /* Cons */ 0,
      _0: {
        TAG: /* PartAt */ 3,
        _0: i,
        _1: param._0
      },
      _1: partition_cols_aux({
        TAG: /* S */ 0,
        _0: i
      }, param._1)
    };
  }
}

function partition_row(id, xs) {
  return make_row(id, {
    TAG: /* Cons */ 0,
    _0: /* PickOne */ 0,
    _1: partition_cols_aux(/* O */ 0, xs)
  });
}

function partition_problem(n) {
  return {
    primary_items: {
      TAG: /* Cons */ 0,
      _0: /* PickOne */ 0,
      _1: /* Nil */ 0
    },
    rows: map((function (pat) {
      return partition_row(pat._0, pat._1);
    }), indexed$1(partitions_of(n)))
  };
}

function has_k_parts(k, xs) {
  return eqb$1(length(xs), k);
}

function is_partition_of_k(n, k, xs) {
  const match = is_partition_of(n, xs);
  if (match === /* True */ 0) {
    return eqb$1(length(xs), k);
  } else {
    return /* False */ 1;
  }
}

function partitions_of_k(n, k) {
  return filter((function (param) {
    return is_partition_of_k(n, k, param);
  }), partitions_bounded({
    TAG: /* S */ 0,
    _0: n
  }, n, n));
}

function partition_problem_k(n, k) {
  return {
    primary_items: {
      TAG: /* Cons */ 0,
      _0: /* PickOne */ 0,
      _1: /* Nil */ 0
    },
    rows: map((function (pat) {
      return partition_row(pat._0, pat._1);
    }), indexed$1(partitions_of_k(n, k)))
  };
}

function subsets(param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return {
      TAG: /* Cons */ 0,
      _0: /* Nil */ 0,
      _1: /* Nil */ 0
    };
  }
  const x = param._0;
  const ss = subsets(param._1);
  return app(ss, map((function (s) {
    return {
      TAG: /* Cons */ 0,
      _0: x,
      _1: s
    };
  }), ss));
}

function nonempty_subsets(xs) {
  return filter((function (s) {
    return negb(eqb$1(length(s), /* O */ 0));
  }), subsets(xs));
}

function set_partition_row(id, xs) {
  return make_row(id, map((function (x) {
    return {
      TAG: /* Value */ 1,
      _0: x
    };
  }), xs));
}

function generated_set(n) {
  return seq(/* O */ 0, n);
}

function set_partition_problem_values(elems) {
  return {
    primary_items: map((function (x) {
      return {
        TAG: /* Value */ 1,
        _0: x
      };
    }), elems),
    rows: map((function (pat) {
      return set_partition_row(pat._0, pat._1);
    }), indexed$1(nonempty_subsets(elems)))
  };
}

function set_partition_problem_generated(n) {
  return set_partition_problem_values(seq(/* O */ 0, n));
}

function set_partition_k_row(n, slot, block_id, xs) {
  return make_row(add(mul(slot, pow({
    TAG: /* S */ 0,
    _0: {
      TAG: /* S */ 0,
      _0: /* O */ 0
    }
  }, n)), block_id), {
    TAG: /* Cons */ 0,
    _0: {
      TAG: /* Slot */ 0,
      _0: slot
    },
    _1: map((function (x) {
      return {
        TAG: /* Value */ 1,
        _0: x
      };
    }), xs)
  });
}

function set_partition_k_rows_values(k, elems) {
  const n = length(elems);
  const blocks = indexed$1(nonempty_subsets(elems));
  return flat_map((function (s) {
    return map((function (pat) {
      return set_partition_k_row(n, s, pat._0, pat._1);
    }), blocks);
  }), seq(/* O */ 0, k));
}

function set_partition_k_problem_values(k, elems) {
  return {
    primary_items: app(slots(k), map((function (x) {
      return {
        TAG: /* Value */ 1,
        _0: x
      };
    }), elems)),
    rows: set_partition_k_rows_values(k, elems)
  };
}

function set_partition_k_problem_generated(k, n) {
  return set_partition_k_problem_values(k, seq(/* O */ 0, n));
}

function multiset_partition_row(id, xs) {
  return make_row(id, map((function (x) {
    return {
      TAG: /* Occur */ 2,
      _0: x
    };
  }), xs));
}

function generated_multiset(n, label_count) {
  if (/* tag */ typeof label_count === "number" || typeof label_count === "string") {
    return /* Nil */ 0;
  } else {
    return map((function (i) {
      return modulo(i, label_count);
    }), seq(/* O */ 0, n));
  }
}

function multiset_partition_problem(values0) {
  const n = length(values0);
  const occs = seq(/* O */ 0, n);
  return {
    primary_items: occurs(n),
    rows: map((function (pat) {
      return multiset_partition_row(pat._0, pat._1);
    }), indexed$1(nonempty_subsets(occs)))
  };
}

function multiset_partition_problem_generated(n, label_count) {
  return multiset_partition_problem(generated_multiset(n, label_count));
}

function multiset_partition_k_row(n, slot, block_id, xs) {
  return make_row(add(mul(slot, pow({
    TAG: /* S */ 0,
    _0: {
      TAG: /* S */ 0,
      _0: /* O */ 0
    }
  }, n)), block_id), {
    TAG: /* Cons */ 0,
    _0: {
      TAG: /* Slot */ 0,
      _0: slot
    },
    _1: map((function (x) {
      return {
        TAG: /* Occur */ 2,
        _0: x
      };
    }), xs)
  });
}

function multiset_partition_k_rows(k, values0) {
  const n = length(values0);
  const occs = seq(/* O */ 0, n);
  const blocks = indexed$1(nonempty_subsets(occs));
  return flat_map((function (s) {
    return map((function (pat) {
      return multiset_partition_k_row(n, s, pat._0, pat._1);
    }), blocks);
  }), seq(/* O */ 0, k));
}

function multiset_partition_k_problem(k, values0) {
  const n = length(values0);
  return {
    primary_items: app(slots(k), occurs(n)),
    rows: multiset_partition_k_rows(k, values0)
  };
}

function multiset_partition_k_problem_generated(k, n, label_count) {
  return multiset_partition_k_problem(k, generated_multiset(n, label_count));
}

function diag2(n, r, c) {
  return add(r, sub(sub(n, {
    TAG: /* S */ 0,
    _0: /* O */ 0
  }), c));
}

function queen_id(n, r, c) {
  return add(mul(r, n), c);
}

function queen_row(n, r, c) {
  return make_row(queen_id(n, r, c), {
    TAG: /* Cons */ 0,
    _0: {
      TAG: /* QRow */ 4,
      _0: r
    },
    _1: {
      TAG: /* Cons */ 0,
      _0: {
        TAG: /* QCol */ 5,
        _0: c
      },
      _1: {
        TAG: /* Cons */ 0,
        _0: {
          TAG: /* QDiag1 */ 6,
          _0: add(r, c)
        },
        _1: {
          TAG: /* Cons */ 0,
          _0: {
            TAG: /* QDiag2 */ 7,
            _0: diag2(n, r, c)
          },
          _1: /* Nil */ 0
        }
      }
    }
  });
}

function queen_rows(n) {
  return flat_map((function (r) {
    return map((function (c) {
      return queen_row(n, r, c);
    }), seq(/* O */ 0, n));
  }), seq(/* O */ 0, n));
}

function qrows(n) {
  return map((function (x) {
    return {
      TAG: /* QRow */ 4,
      _0: x
    };
  }), seq(/* O */ 0, n));
}

function qcols(n) {
  return map((function (x) {
    return {
      TAG: /* QCol */ 5,
      _0: x
    };
  }), seq(/* O */ 0, n));
}

function nqueens_problem(n) {
  return {
    primary_items: app(qrows(n), qcols(n)),
    rows: queen_rows(n)
  };
}

function langford_slots(n) {
  return map((function (x) {
    return {
      TAG: /* Slot */ 0,
      _0: x
    };
  }), seq(/* O */ 0, mul({
    TAG: /* S */ 0,
    _0: {
      TAG: /* S */ 0,
      _0: /* O */ 0
    }
  }, n)));
}

function langford_values(n) {
  return map((function (x) {
    return {
      TAG: /* Value */ 1,
      _0: x
    };
  }), seq({
    TAG: /* S */ 0,
    _0: /* O */ 0
  }, n));
}

function langford_row_id(n, k, start) {
  return add(mul(sub(k, {
    TAG: /* S */ 0,
    _0: /* O */ 0
  }), mul({
    TAG: /* S */ 0,
    _0: {
      TAG: /* S */ 0,
      _0: /* O */ 0
    }
  }, n)), start);
}

function langford_second_pos(k, start) {
  return add(add(start, k), {
    TAG: /* S */ 0,
    _0: /* O */ 0
  });
}

function langford_start_count(n, k) {
  return sub(sub(mul({
    TAG: /* S */ 0,
    _0: {
      TAG: /* S */ 0,
      _0: /* O */ 0
    }
  }, n), k), {
    TAG: /* S */ 0,
    _0: /* O */ 0
  });
}

function langford_row(n, k, start) {
  return make_row(langford_row_id(n, k, start), {
    TAG: /* Cons */ 0,
    _0: {
      TAG: /* Slot */ 0,
      _0: start
    },
    _1: {
      TAG: /* Cons */ 0,
      _0: {
        TAG: /* Slot */ 0,
        _0: langford_second_pos(k, start)
      },
      _1: {
        TAG: /* Cons */ 0,
        _0: {
          TAG: /* Value */ 1,
          _0: k
        },
        _1: /* Nil */ 0
      }
    }
  });
}

function langford_rows_for_value(n, k) {
  return map((function (start) {
    return langford_row(n, k, start);
  }), seq(/* O */ 0, langford_start_count(n, k)));
}

function langford_rows(n) {
  return flat_map((function (k) {
    return langford_rows_for_value(n, k);
  }), seq({
    TAG: /* S */ 0,
    _0: /* O */ 0
  }, n));
}

function langford_problem(n) {
  return {
    primary_items: app(langford_slots(n), langford_values(n)),
    rows: langford_rows(n)
  };
}

function colorings(n, q) {
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    return {
      TAG: /* Cons */ 0,
      _0: /* Nil */ 0,
      _1: /* Nil */ 0
    };
  }
  const n$p = n._0;
  return flat_map((function (color) {
    return map((function (rest) {
      return {
        TAG: /* Cons */ 0,
        _0: color,
        _1: rest
      };
    }), colorings(n$p, q));
  }), seq(/* O */ 0, q));
}

function progression(start, step, k) {
  return map((function (t) {
    return add(start, mul(t, step));
  }), seq(/* O */ 0, k));
}

function progression_in_bounds(n, start, step, k) {
  const n$1 = add(start, mul(sub(k, {
    TAG: /* S */ 0,
    _0: /* O */ 0
  }), step));
  return leb({
    TAG: /* S */ 0,
    _0: n$1
  }, n);
}

function arithmetic_progressions(n, k) {
  return flat_map((function (start) {
    return map((function (step) {
      return progression(start, step, k);
    }), filter((function (step) {
      return progression_in_bounds(n, start, step, k);
    }), seq({
      TAG: /* S */ 0,
      _0: /* O */ 0
    }, n)));
  }), seq(/* O */ 0, n));
}

function same_color_at(colors, color, pos) {
  const c = nth_error(colors, pos);
  if (c !== undefined) {
    return eqb$1(c, color);
  } else {
    return /* False */ 1;
  }
}

function monochromatic_progression(colors, param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* False */ 1;
  }
  const color = nth_error(colors, param._0);
  if (color !== undefined) {
    return forallb((function (param) {
      return same_color_at(colors, color, param);
    }), param._1);
  } else {
    return /* False */ 1;
  }
}

function has_monochromatic_progression(n, param, k, colors) {
  return existsb((function (param) {
    return monochromatic_progression(colors, param);
  }), arithmetic_progressions(n, k));
}

function waerden_good_coloring(n, q, k, colors) {
  return negb(has_monochromatic_progression(n, q, k, colors));
}

function waerden_good_colorings(n, q, k) {
  return filter((function (param) {
    return waerden_good_coloring(n, q, k, param);
  }), colorings(n, q));
}

function coloring_cols_aux(pos, param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return /* Nil */ 0;
  } else {
    return {
      TAG: /* Cons */ 0,
      _0: {
        TAG: /* PartAt */ 3,
        _0: pos,
        _1: param._0
      },
      _1: coloring_cols_aux({
        TAG: /* S */ 0,
        _0: pos
      }, param._1)
    };
  }
}

function waerden_coloring_row(id, colors) {
  return make_row(id, {
    TAG: /* Cons */ 0,
    _0: /* PickOne */ 0,
    _1: coloring_cols_aux(/* O */ 0, colors)
  });
}

function waerden_rows(n, q, k) {
  return map((function (pat) {
    return waerden_coloring_row(pat._0, pat._1);
  }), indexed$1(waerden_good_colorings(n, q, k)));
}

function waerden_problem(n, q, k) {
  return {
    primary_items: {
      TAG: /* Cons */ 0,
      _0: /* PickOne */ 0,
      _1: /* Nil */ 0
    },
    rows: waerden_rows(n, q, k)
  };
}

const Combinatorics = {
  ccol_eqb: ccol_eqb,
  coq_Eqb_CCol: ccol_eqb,
  item: item,
  make_row: make_row,
  make_problem: make_problem,
  slots: slots,
  occurs: occurs,
  assignment_id: assignment_id,
  tuple_row: tuple_row,
  assignment_rows_tuple: assignment_rows_tuple,
  tuple_problem: tuple_problem,
  permutation_row: permutation_row,
  assignment_rows_permutation: assignment_rows_permutation,
  permutation_problem: permutation_problem,
  combinations_from: combinations_from,
  combinations: combinations,
  combination_cols_aux: combination_cols_aux,
  combination_row: combination_row,
  indexed: indexed$1,
  combination_problem: combination_problem,
  sum_nat: sum_nat,
  nonincreasing_from: nonincreasing_from,
  nonincreasing: nonincreasing,
  is_partition_of: is_partition_of,
  partitions_bounded: partitions_bounded,
  partitions_of: partitions_of,
  partition_cols_aux: partition_cols_aux,
  partition_row: partition_row,
  partition_problem: partition_problem,
  has_k_parts: has_k_parts,
  is_partition_of_k: is_partition_of_k,
  partitions_of_k: partitions_of_k,
  partition_problem_k: partition_problem_k,
  subsets: subsets,
  nonempty_subsets: nonempty_subsets,
  set_partition_row: set_partition_row,
  generated_set: generated_set,
  set_partition_problem_values: set_partition_problem_values,
  set_partition_problem_generated: set_partition_problem_generated,
  set_partition_k_row: set_partition_k_row,
  set_partition_k_rows_values: set_partition_k_rows_values,
  set_partition_k_problem_values: set_partition_k_problem_values,
  set_partition_k_problem_generated: set_partition_k_problem_generated,
  multiset_partition_row: multiset_partition_row,
  generated_multiset: generated_multiset,
  multiset_partition_problem: multiset_partition_problem,
  multiset_partition_problem_generated: multiset_partition_problem_generated,
  multiset_partition_k_row: multiset_partition_k_row,
  multiset_partition_k_rows: multiset_partition_k_rows,
  multiset_partition_k_problem: multiset_partition_k_problem,
  multiset_partition_k_problem_generated: multiset_partition_k_problem_generated,
  diag1: add,
  diag2: diag2,
  queen_id: queen_id,
  queen_row: queen_row,
  queen_rows: queen_rows,
  qrows: qrows,
  qcols: qcols,
  nqueens_problem: nqueens_problem,
  langford_slots: langford_slots,
  langford_values: langford_values,
  langford_row_id: langford_row_id,
  langford_second_pos: langford_second_pos,
  langford_start_count: langford_start_count,
  langford_row: langford_row,
  langford_rows_for_value: langford_rows_for_value,
  langford_rows: langford_rows,
  langford_problem: langford_problem,
  colorings: colorings,
  progression: progression,
  progression_in_bounds: progression_in_bounds,
  arithmetic_progressions: arithmetic_progressions,
  color_at: nth_error,
  same_color_at: same_color_at,
  monochromatic_progression: monochromatic_progression,
  has_monochromatic_progression: has_monochromatic_progression,
  waerden_good_coloring: waerden_good_coloring,
  waerden_good_colorings: waerden_good_colorings,
  coloring_cols_aux: coloring_cols_aux,
  waerden_coloring_row: waerden_coloring_row,
  waerden_rows: waerden_rows,
  waerden_problem: waerden_problem
};

function solve_ids_combinatorics(fuel, p) {
  return solve_ids(ccol_eqb, eqb$1, fuel, p);
}

function solve_ids_sudoku(fuel, p) {
  return solve_ids(gcol_eqb, eqb$1, fuel, p);
}

function solve_ids_warehouse(fuel, p) {
  return solve_ids(eqb1, eqb1, fuel, p);
}

function api_nqueens_ids(fuel, n) {
  return solve_ids_combinatorics(fuel, nqueens_problem(n));
}

function api_langford_ids(fuel, n) {
  return solve_ids_combinatorics(fuel, langford_problem(n));
}

function api_waerden_ids(fuel, n, q, k) {
  return solve_ids_combinatorics(fuel, waerden_problem(n, q, k));
}

function api_tuple_ids(fuel, k, n) {
  return solve_ids_combinatorics(fuel, tuple_problem(k, n));
}

function api_permutation_ids(fuel, k, n) {
  return solve_ids_combinatorics(fuel, permutation_problem(k, n));
}

function api_combination_ids(fuel, k, n) {
  return solve_ids_combinatorics(fuel, combination_problem(k, n));
}

function api_partition_ids(fuel, n) {
  return solve_ids_combinatorics(fuel, partition_problem(n));
}

function api_partition_k_ids(fuel, n, k) {
  return solve_ids_combinatorics(fuel, partition_problem_k(n, k));
}

function api_set_partition_generated_ids(fuel, n) {
  return solve_ids_combinatorics(fuel, set_partition_problem_values(seq(/* O */ 0, n)));
}

function api_set_partition_k_generated_ids(fuel, k, n) {
  return solve_ids_combinatorics(fuel, set_partition_k_problem_generated(k, n));
}

function api_multiset_partition_generated_ids(fuel, n, label_count) {
  return solve_ids_combinatorics(fuel, multiset_partition_problem(generated_multiset(n, label_count)));
}

function api_multiset_partition_k_generated_ids(fuel, k, n, label_count) {
  return solve_ids_combinatorics(fuel, multiset_partition_k_problem_generated(k, n, label_count));
}

function api_sudoku_exact_ids(fuel, r, c, r0, c0) {
  return solve_ids_sudoku(fuel, generalized_sudoku_problem_exact(r, c, r0, c0));
}

function api_sudoku_at_most_ids(fuel, r, c, r0, c0) {
  return solve_ids_sudoku(fuel, generalized_sudoku_problem_at_most(r, c, r0, c0));
}

function api_warehouse_guaranteed_ids(fuel, n_items, n_sources, k) {
  return solve_ids_warehouse(fuel, guaranteed_k_problem(n_items, n_sources, k));
}

function api_warehouse_guaranteed_colored_ids(fuel, n_items, n_sources, n_product_colors, n_source_reqs, k) {
  return solve_ids_warehouse(fuel, guaranteed_k_colored_problem(n_items, n_sources, n_product_colors, n_source_reqs, k));
}

const PublicAPI = {
  solve_ids_combinatorics: solve_ids_combinatorics,
  solve_ids_sudoku: solve_ids_sudoku,
  solve_ids_warehouse: solve_ids_warehouse,
  api_nqueens_ids: api_nqueens_ids,
  api_langford_ids: api_langford_ids,
  api_waerden_ids: api_waerden_ids,
  api_tuple_ids: api_tuple_ids,
  api_permutation_ids: api_permutation_ids,
  api_combination_ids: api_combination_ids,
  api_partition_ids: api_partition_ids,
  api_partition_k_ids: api_partition_k_ids,
  api_set_partition_generated_ids: api_set_partition_generated_ids,
  api_set_partition_k_generated_ids: api_set_partition_k_generated_ids,
  api_multiset_partition_generated_ids: api_multiset_partition_generated_ids,
  api_multiset_partition_k_generated_ids: api_multiset_partition_k_generated_ids,
  api_sudoku_exact_ids: api_sudoku_exact_ids,
  api_sudoku_at_most_ids: api_sudoku_at_most_ids,
  api_warehouse_guaranteed_ids: api_warehouse_guaranteed_ids,
  api_warehouse_guaranteed_colored_ids: api_warehouse_guaranteed_colored_ids
};

export {
  negb,
  fst,
  snd,
  length,
  app,
  add,
  mul,
  sub,
  eqb,
  Nat,
  map,
  seq,
  nth_error,
  rev,
  flat_map,
  fold_left,
  existsb,
  forallb,
  filter,
  find,
  combine,
  eqb0,
  eqb1,
  append,
  GDance,
  SudokuProblem,
  Guaranteed_K_Warehouse,
  Combinatorics,
  PublicAPI,
}
/* No side effect */
